# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

ENV container=docker
RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python3 sudo bash ca-certificates iproute2 systemd && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf -y install python3 sudo bash iproute systemd && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute systemd && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi
RUN if [ -f /lib/systemd/systemd ]; then \
        (cd /lib/systemd/system/sysinit.target.wants/; \
          for i in *; do \
            [ "$i" = systemd-tmpfiles-setup.service ] && continue; \
            rm -f "$i"; \
          done); \
        (cd /usr/lib/systemd/system/multi-user.target.wants/; \
          for i in *; do \
            [ "$i" = systemd-user-sessions.service ] && continue; \
            rm -f "$i"; \
          done); \
        rm -f /etc/systemd/system/*.wants/*; \
        rm -f /lib/systemd/system/local-fs.target.wants/*; \
        rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
        rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
        rm -f /lib/systemd/system/basic.target.wants/*; \
        rm -f /lib/systemd/system/anaconda.target.wants/*; \
    fi

CMD ["/lib/systemd/systemd"]
